### ISSUE TITLE
Export 404s

### ISSUE THREAD

**Issue by vegetrader** [ocodia/Check-My-Links#12]
Hello,
This is by far the best 404 checker tool.
However, on pages with loads of broken links, is there a convenient way to export all the 404 URLs somehow? Either to clipboard or excel?

Any automated way to export the 404'd URLs that CheckMyLinks picks up would make life a lot easier!

**Comment by kyleladd** [comment]
The best I've been able to do so far is:
1) Button to export bad links (exports to console in csv format)
2) Copy from console and paste into text editor
3) Save as .csv file
4) Open file in Excel

What do you think it should export (element properties etc.)?
- element.getattribute(href)
- element.outerHTML


Thanks,
