### ISSUE TITLE
Check for broken fragments (or at least indicate they're unknown)

### ISSUE THREAD

**Issue by maxlinc** [ocodia/Check-My-Links#16]
Check-My-Links doesn't properly support [URI fragments](http://en.wikipedia.org/wiki/Fragment_identifier) (the portion of the URL after `#`). For example, these URLs were given in a similar [issue for drupal's linkchecker](https://www.drupal.org/node/1875602):

```
http://drupal.org/node/123456#comment-form
http://drupal.org/?q=node/123456#comment-form
http://drupal.org/?q=node/123456#comment-654321
```

It's even more important when you have a relative URI starting with a fragment, used for navigation within a page. Note the links to local fragments in the snippet below, from a wikipedia article's table of contents:

```html
<ul>
<li class="toclevel-1 tocsection-1"><a href="#Globular_cluster"><span class="tocnumber">1</span> <span class="toctext">Globular cluster</span></a></li>
<li class="toclevel-1 tocsection-2"><a href="#Intermediate_forms"><span class="tocnumber">2</span> <span class="toctext">Intermediate forms</span></a></li>
<li class="toclevel-1 tocsection-3"><a href="#Open_clusters"><span class="tocnumber">3</span> <span class="toctext">Open clusters</span></a>
<ul>
<li class="toclevel-2 tocsection-4"><a href="#Super_star_cluster"><span class="tocnumber">3.1</span> <span class="toctext">Super star cluster</span></a></li>
<li class="toclevel-2 tocsection-5"><a href="#Embedded_cluster"><span class="tocnumber">3.2</span> <span class="toctext">Embedded cluster</span></a></li>
</ul>
</li>
<li class="toclevel-1 tocsection-6"><a href="#Stellar_associations"><span class="tocnumber">4</span> <span class="toctext">Stellar associations</span></a></li>
<li class="toclevel-1 tocsection-7"><a href="#Astronomical_significance_of_clusters"><span class="tocnumber">5</span> <span class="toctext">Astronomical significance of clusters</span></a></li>
<li class="toclevel-1 tocsection-8"><a href="#See_also"><span class="tocnumber">6</span> <span class="toctext">See also</span></a></li>
<li class="toclevel-1 tocsection-9"><a href="#References"><span class="tocnumber">7</span> <span class="toctext">References</span></a></li>
<li class="toclevel-1 tocsection-10"><a href="#External_links"><span class="tocnumber">8</span> <span class="toctext">External links</span></a></li>
</ul>
```

Check-My-Links will "check" that these links (e.g. `#Astronomical_significance_of_clusters`) work, but it is not really doing anything. It always highlights links to fragments in green, even if the target page fragment does not exist. It seems to be ignoring the fragment, effectively treating all the links as equivalent to `#`, or just checking the truism that the current page exists.

My desired behavior would be to either:
1. Check link fragments go to a valid page fragment, marked via element ids or `<a name="...">`, so that broken fragments are marked in red.
Note: this may only be desirable for links that return HTML. Other media types may use fragments for a different purpose - for example [PDFs use it to specify a page number](https://www.drupal.org/node/2088461)
2. Indicate that the status of links containing relative fragments is unknown, perhaps marking them yellow or at least printing a list of unvalidated link fragments to the javascript console.

**Comment by ocodia** [comment]
Hi @maxlinc, URI Fragments are now validated correctly in the latest release.
