### ISSUE TITLE
link export feature

### ISSUE THREAD

**Issue by ryosax** [ocodia/Check-My-Links#17]
it'd be nice if we could export the link list.

**Comment by kyleladd** [comment]
The best I've been able to do so far is:
1) Button to export bad links (exports to console in csv format)
2) Copy from console and paste into text editor
3) Save as .csv file
4) Open file in Excel

What do you think it should export?
- href attribute
- element.outerHTML

Thanks,

**Comment by ryosax** [comment]
yes, i think it'd be perfect a button like that.

i think it should export url & anchor text for textual links or url & a tag
(say [IMG]) for image links (even better adding the img alt tag, if
present).

thanks
 r


2015-10-16 4:51 GMT+02:00 Kyle Ladd <notifications@github.com>:

> The best I've been able to do so far is:
> 1) Button to export bad links (exports to console in csv format)
> 2) Copy from console and paste into text editor
> 3) Save as .csv file
> 4) Open file in Excel
>
> What do you think it should export?
>
>    - href attribute
>    - element.outerHTML
>
> Thanks,
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ocodia/Check-My-Links/issues/17#issuecomment-148583560>
> .
>



-- 
* Rino S Sassi*



*Int *050 72 10 286
*Mob* 338 29 89 849

*MILANO  *(20154) - Corso Sempione, 10
*Uff* 02 83 41 21 10

*PISA *(56121) - Via Scornigiana, 9
*Uff* 050 98 54 55 - *Fax* 050 38 69 448

*www.fortop.it <http://www.fortop.it>*

**Comment by ocodia** [comment]
Latest version includes CSV export to console.

**Comment by ryosax** [comment]
great work, thanks!

 r


2015-10-26 15:36 GMT+01:00 Paul <notifications@github.com>:

> Closed #17 <https://github.com/ocodia/Check-My-Links/issues/17>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ocodia/Check-My-Links/issues/17#event-445601063>.
>



-- 
* Rino S Sassi*



*Mob* 338 29 89 849

*MILANO  *(20154) - Corso Sempione, 10
*Uff* 02 83 41 21 10

*PISA *(56121) - Via Scornigiana, 9
*Fax* 050 38 69 448

*www.fortop.it <http://www.fortop.it>*
