### ISSUE TITLE
Incorrect results showing after the update

### ISSUE THREAD

**Issue by anooppednekar** [ocodia/Check-My-Links#26]
CheckmyLinks is showing incorrect result after the update on 27 April 2015.

Test Steps:
1. Go to http://www.everydayhealth.com/
2. Run CheckMyLinks tool from chrome
3. Observe that the tool shows response code of 404 error while on manual check the page loads properly.
![checkmylinks](https://cloud.githubusercontent.com/assets/12271871/7491836/47345530-f40b-11e4-926c-3c0b3f31e34a.jpg)

**Comment by ocodia** [comment]
Right click on the extension button... click 'Options' and change the 'Method of Request' to "GET", then click on 'Save my preferences'. 

HEAD method requests are quicker, but servers don't always return accurate results when that request type is used.

**Comment by anooppednekar** [comment]
Thank you Ocodia for your prompt response. It's working fine now.
