### ISSUE TITLE
Grey links

### ISSUE THREAD

**Issue by ghost** [ocodia/Check-My-Links#29]
First off, BRILLIANT tool. Thank you!

Second I do have a quick question about a problem that I encountered.

After using the tool for about 50 pages I noticed all the links turn up grey rather than green or red. It seemed to have stopped working. Is there a way to fix that?

You rock,
Ryan

**Comment by kyleladd** [comment]
Do you have caching enabled? If so, try going into the extension's options and clearing the cache.  The data store can be seen in Chrome by:
1) URL: chrome://extensions 
2) Check My Links-Inspect views: background page
3) Resources Tab
4) IndexedDB
5) CheckLinks
6) links
I am suspecting you've exceeded IndexedDB's max storage limit.  In that case, we may have to have the extension automatically remove records that are (X) old or remove starting with the oldest.
Thanks
