### ISSUE TITLE
Missing 'Allow access to file URLs' checkbox

### ISSUE THREAD

**Issue by srackham** [ocodia/Check-My-Links#31]
This is contrary to the documentation: "Version 3.3.4: Now allows you to
check links in a local file (note this requires the 'Allow access to
file URLs' checkbox to be ticked in the Chrome extensions screen)."

See screenshot (Chrome version 43.0.2357.130 (64-bit))

Adding `"<all_urls>"` to the manifest permissions fixed the problem 
but introduced a new problem: `file:` URLs are not checked.
![screenshot](https://cloud.githubusercontent.com/assets/674468/8318746/b4cb60e0-1a5b-11e5-950e-be07c2a52f9f.png)

**Comment by ocodia** [comment]
Local files can now be checked.
