### ISSUE TITLE
Downloading very large files

### ISSUE THREAD

**Issue by potthast** [ocodia/Check-My-Links#34]
When using the extension on a web page that links to very large files, it sometimes crashes.

At any rate, why does the extensions have to download the files entirely? Why not just make at HTTP HEAD request to avoid downloading the entire file?

**Comment by kyleladd** [comment]
There is a setting on the options page to change between making HEAD requests and GET requests: https://github.com/ocodia/Check-My-Links/blob/master/options.html#L156

**Comment by potthast** [comment]
My bad! Sorry for not checking there, first.
