### ISSUE TITLE
Links to PDF files fail when using page anchors

### ISSUE THREAD

**Issue by potthast** [ocodia/Check-My-Links#35]
The extensions fails to download links of the following form:
http://www.example.com/example.pdf#page=6

The anchor instructs the in-browser PDF viewer to jump to page 6, whereas the extensions should perhaps simply ignore the anchor part of a URL.

**Comment by kyleladd** [comment]
Parsing the hashtags is going to be an option to enable/disable in the upcoming release.  Will be released soon.

Thanks
