### ISSUE TITLE
404 errors with links that include hashtags like accordions

### ISSUE THREAD

**Issue by merrillie** [ocodia/Check-My-Links#40]
Hi

I often use this broken link checker to check our website pages at work.
These says when I use this tool it reports all our accordions and anchor links as broken - anything that has a hashtag in the link.
This is a page you could try - http://www.lib.uts.edu.au/facilities/library-spaces
It has been about 6 months since I did a thorough check and I think I had the same problem then, however this wasn't an issue last year.

Is there anything I can do to stop these showing up as broken when I run the link checker? I couldn't think of a way to add it into the "Exclude links from these domains" section.

**Comment by kyleladd** [comment]
We are in the process of making the parsing after a hashtag an option in the next release
![cml-hashtag](https://cloud.githubusercontent.com/assets/1644131/10523771/1adceaec-734a-11e5-867d-bb0c533ab775.PNG)
