### ISSUE TITLE
Link stays in queue when DNS address could not be found

### ISSUE THREAD

**Issue by Emiliya93** [ocodia/Check-My-Links#51]
For example check the attached image error.
![2016-05-09_1521](https://cloud.githubusercontent.com/assets/10466854/15112922/e6cdf3d8-15f9-11e6-8916-e5cdc51aba2a.png)
![2016-05-09_1523](https://cloud.githubusercontent.com/assets/10466854/15112945/1505db30-15fa-11e6-824d-ae6c35d2c0f0.png)

**Comment by Emiliya93** [comment]
Yesterday I had the same problem - I left the app CheckMyLinks turned on over 10 hours and still I have links that are in the queue. 
It is one specific link that is used on many places and returns error - "This site can’t be reached" and message "examples.xquery.com’s server DNS address could not be found." 
It would be nice if the app can say it's invalid link. 
Thank you for your time.
Here are some screenshots for reference:
![2016-07-08_1356](https://cloud.githubusercontent.com/assets/10466854/16685588/bf44e89a-4514-11e6-9c39-9550400858f4.png)

![2016-07-08_1355](https://cloud.githubusercontent.com/assets/10466854/16685578/ae025bc6-4514-11e6-8f86-8a2fa4312780.png)

**Comment by kyleladd** [comment]
Here's my latest: https://github.com/kyleladd/Check-My-Links/tree/KL/Merging  
There shouldn't be any links being left in queue.  More accurate timeouts still need to be worked on but things being left in queue is a different issue that should be fixed on the provided branch.

Installing an extension from GitHub: https://blog.emailhunter.co/install-chrome-extension-manually/
Here's the zip: https://github.com/kyleladd/Check-My-Links/archive/KL/Merging.zip

**Comment by Emiliya93** [comment]
Thank you for the quick response.

I'll wait for the new version coming in Chrome Store then :)

Have a great day!
Emiliya

**Comment by kyleladd** [comment]
I don't know when that'll be. Only Ocodia can publish it to the Chrome Store, but I'm sure he'd welcome additional beta testers/reviewers before merging in pull requests.

Thanks for your assistance,

Kyle
