### ISSUE TITLE
Export to console button not working

### ISSUE THREAD

**Issue by sungodly** [ocodia/Check-My-Links#53]
Using Chrome Version 51.0.2704.63 m on a Windows 7 PC. Clicking the export to console button does nothing. Any potential conflicts I should look for?

**Comment by ocodia** [comment]
Export to console only works when the console is shown (see '[Advanced](https://github.com/ocodia/Check-My-Links/wiki#advanced)' section of Wiki on how to show console) and will only list broken links.
