### ISSUE TITLE
Ability to exclude own website

### ISSUE THREAD

**Issue by kasperore** [ocodia/Check-My-Links#56]
I like your plug-in. I had some things i thought you could add. I saw some of these points in the issue list, like a time out for a link so it checks all links and not just staying at one trying to check it. Maybe add it to a timeout list with different color?
i thought it would come in handy to make an option to exclude the website you are on, without having to put the link in the exclude list. 
I also had an issue occure where the plug-in found 800 links and checked 1000.
That's it for now.

Keep it up!

**Comment by kyleladd** [comment]
"found 800 links and checked 1000" - I suspect this happened when the extension was clicked to start checking the page and then was clicked again before completing the first click's run through of checking all of the links on the page. I believe we're not aborting existing uncompleted requests when the button is clicked a second time, only resetting the DOM CheckMyLinks classes.
