### ISSUE TITLE
Initial options tab after installation

### ISSUE THREAD

**Issue by desertjedi85** [ocodia/Check-My-Links#62]
Both Trailing '#' (href="#"):  & Empty Link (href=""):  have the same description, see below:

Warnings

Parse DOM after hashtag (#):  
Hashtags can link to elements by id within the DOM. Enabling will add add the check to make sure an element exists by id to correspond to the hashtag. When enabled, if the page resolves but the corresponding element is not found, the element will be marked as a warning and shown in the console.log (F12->Console tab). Request Type: GET is required

Trailing '#' (href="#"):  
When enabled, if the link url endswith '#' you will be warned.

Empty Link (href=""):  
When enabled, if the link url endswith '#' you will be warned.

**Comment by ocodia** [comment]
Fixed in #48
