### ISSUE TITLE
2 items in queue...stuck

### ISSUE THREAD

**Issue by newmarket2** [ocodia/Check-My-Links#63]
In Chrome, ran against our home page which is going live over the weekend.
2 items remained in the queue.  Why didn't it complete?
I know there's one link with a 404 and I was expecting it to show up as a failure, but it's still in the queue.
And, I have no idea if the 2nd item in the queue is a problem or not

**Comment by kyleladd** [comment]
I believe the fix just hasn't been merged in and deployed yet. I think it is within an open pull request.

You can give this branch a try: https://github.com/kyleladd/Check-My-Links/tree/KL/Merging
I believe this is a branch where I merged all the open pull requests: https://github.com/ocodia/Check-My-Links/pulls

I believe the issue you are encountering was fixed: https://github.com/kyleladd/Check-My-Links/commit/35120ddeaa0f47a5ebed36daafdbfaab7fb4ddc6  and/or https://github.com/kyleladd/Check-My-Links/commit/973892b1822795fb5b695ea6d192b576adfdf3fd

Loading unpacked extensions:
1. Visit chrome://extensions (via omnibox or menu -> Tools -> Extensions).
2. Enable Developer mode by ticking the checkbox in the upper-right corner.
3. Click on the "Load unpacked extension..." button.
4. Select the directory containing your unpacked extension. (where you cloned this repo and checked out the branch `git clone https://github.com/kyleladd/Check-My-Links.git && git checkout KL/Merging`)

**Comment by newmarket2** [comment]
I get the gist but not in detail.

Let’s see if I understand:

 

You know about this problem.

You think you have a fix, but it’s not been pushed to your production verstion.

 

You gave me steps to do something called “unpacked extensions”.  I will try to follow them, but I don’t know what “unpacked extentions” are.  Your extension is there and does work, so is it a new version that might not have “unpacked”?

**Comment by newmarket2** [comment]
There is still 1 item left in the queue when I run.

I’m running v 3.6.1 which looks like the current version.

 

If your email below is still a solution….you’ll have to explain it with a bit more step-by-step because I don’t understand it

**Comment by ocodia** [comment]
Fixed in #68
