### ISSUE TITLE
Empty link description wrong. 

### ISSUE THREAD

**Issue by Luen** [ocodia/Check-My-Links#64]
This is the way it currently looks:
Trailing '#' (href="#"):  
When enabled, if the link url endswith '#' you will be warned.

Empty Link (href=""):  
When enabled, if the link url endswith '#' you will be warned.

Empty link description should be something like "When enabled, if the link url is blank you will be warned."

**Comment by ocodia** [comment]
Thanks. @kyleladd fixed in #48.
