### ISSUE TITLE
click the icon in Chrome, nothign happens

### ISSUE THREAD

**Issue by pinkflamingoTX** [ocodia/Check-My-Links#65]
I downloaded the extension and updated the options successfully, but when I go to my website (or any website) and CLICK the "Check my links" icon in my toolbar, nothing happens. I also tried reverting to just the default plugin options, still nothing happens.

**Comment by kyleladd** [comment]
I haven't been able to reproduce, but we can look at a few things to hopefully pinpoint the issue.
First, we can check the Chrome version via: [chrome://help/](chrome://help/)
Next, we can open two consoles to see if there are any errors.
1 - Press F12 to open the console on the current page you intend on checking
2- In another tab, Navigate to 
[chrome://extensions/](chrome://extensions/) (Please note the version of the Check My Links extension too)
Click on the background page view of Check My Links - Inspect views: background page
Now, watch to see if any errors are logged while you click the Check My Links icon in either console.

Thanks

**Comment by pinkflamingoTX** [comment]
Thanks for getting back to me. I did as you asked and here are the versions
of each software:

Chrome Version 57.0.2987.133
[image: Inline image 1]


and I follow through F12 to "view source" for the page I want to check
links on, BUT i have no idea what you mean by this

*"Click on the background page view of Check My Links - Inspect views:
background page*
Now, watch to see if any errors are logged while you click the Check My
Links icon in either console."

ᐧ

*Jana Sunshine*
323-898-6199 | jana.z.sunshine@gmail.com | Skype: j.sun.inc
<https://mail.google.com/mail/u/0/#>

**Comment by kyleladd** [comment]
https://youtu.be/j9VZw9ERh7Y
Used "F12" to bring up the developer tools in the current window (Also is `Ctrl + Chift + I`)- I am on the console tab

lol, I didn't expect to find a 404 on Android.com, but I guess that is a good demo of the intended functionality.
