### ISSUE TITLE
queue goes into negatives

### ISSUE THREAD

**Issue by Arosenthalbauer** [ocodia/Check-My-Links#67]
while i was checking a page for broken links the extension was saying that there were 358 links, 918 valid links, and -202 links in the queue  
![image](https://cloud.githubusercontent.com/assets/28623065/25946154/9d77badc-3652-11e7-99c4-2f52a06aded4.png)

**Comment by kyleladd** [comment]
Perhaps you double clicked or clicked again while it was already running but not finished with the previous check.  The previous run's promises are not getting cleared and adjusting the displayed counters (which are getting reset on click) even though they are no longer relevant.

**Comment by ocodia** [comment]
This is a common outcome of (perhaps accidentally) clicking on the extension twice. I'm going to close this one just now until more details are provided.
