### ISSUE TITLE
Suggestion: log warnings and errors to browser console

### ISSUE THREAD

**Issue by jasonkarns** [ocodia/Check-My-Links#77]
Not all links are visible all the time. So this extension seems to report link errors/warnings that are unable to be seen. (Seeing an Error or Warning in the extension, but no way to find the broken link is rather frustrating.)

Otherwise, great extension!

**Comment by jasonkarns** [comment]
apparently they _are_ logged to console, but it needed refreshing... still unable to trace the log message back to the element that triggered it. Would be nice to include the dom element in the log invocation so i could click straight to the broken element.

**Comment by ocodia** [comment]
> Would be nice to include the dom element in the log invocation so i could click straight to the broken element.

Excellent idea.
