### ISSUE TITLE
Checking #-anchors does not seem to give expected results

### ISSUE THREAD

**Issue by CasperLange** [ocodia/Check-My-Links#78]
I use #-links a lot. This extension seems to be the only link checker that includes anchor checking.
To check these anchors I activated "Parse DOM after hashtag"

When I check this link "https://wiki.afasnext.com/wikipagina/47833ae6-d16b-4257-8a33-31fe5e3fac19#FieldName" it is marked as warning: 200
HTML-code 200 seems to be "everything OK". Indeed, this anchor does exist on the target page.
Whys is this linked marked yellow?

When I check "https://wiki.afasnext.com/wikipagina/47833ae6-d16b-4257-8a33-31fe5e3fac19#FieldNam" it is also marked as warning: 200. This should be an error, because the id "fieldnam" does not exist on the target page.

Am I doing something wrong?

**Comment by ocodia** [comment]
Sorry, I can't see your links. Either way: When 'Parse DOM after hashtag' is enabled, if the page resolves ok (valid URL) but the corresponding element ID is not found, the element will be marked as a warning (yellow).
