### ISSUE TITLE
not reporting missing domains as errors

### ISSUE THREAD

**Issue by g1001** [ocodia/Check-My-Links#79]
Link checked one of my pages today at www.canals.com and then did a manual check for comparison, since a site visitor had emailed me about broken links. check-my-links showed all OK, but there were a number that were actually NOT.  These were mostly sites for which the domain name was no longer valid.  It's possible these bad links were being shown as redirected links, rather than invalid, but I unfortunately did not pay enough attention while I was fixing them.  There were quite a few, which makes me think this link checking problem may have existed for a while.

**Comment by g1001** [comment]
OK, here are two links whose domains have vanished, but check-my-links shows them in lighter green as valid redirects:
<a href="http://www.cromfordcanal.org.uk/">Friends of the Cromford Canal</a>
<a href="http://www.norburycruisingclub.co.uk/">Norbury Cruising Club</a>
When the first, for example, is visited in chrome, chrome displays "This site can’t be reached
www.cromfordcanal.org.uk’s server IP address could not be found..  Same for the other page.
Hope this helps.

**Comment by ocodia** [comment]
Those URLs don't resolve anywhere, so there is no server to officially respond to the HTTP request. Therefore they're assumed valid. I agree this isn't the right response, will try and look into this next time I get a chance. Thanks.
