### ISSUE TITLE
Invalid Links not highlighted

### ISSUE THREAD

**Issue by scottwhatever** [ocodia/Check-My-Links#83]
Hi, Great extension. Works well with Papaly. Only problem is the invalid links are not highlighted in red so don't know which links are invalid.

Scott

**Comment by scottwhatever** [comment]
Hi, I'm using Papaly to store all my personal bookmarks and have many links. See screenshot
![image](https://user-images.githubusercontent.com/8837348/39081767-1b5cdeea-453f-11e8-9796-afc791773212.png)
As you can see it showing 3 invalid links but nothing is highlighted in red. I have noticed that when I click on each of the categories (bookmark folders) down the left side I get 1 invalid link on each page each time, but nothing highlighted. 
I'll give the link here for the page above: [https://papaly.com/#board_id=a397e6d4c3934be586905c73d15ff4c0](url)
Cheers,
Scott

**Comment by briscradley** [comment]
Hey, I am getting a valid redirecting link on a 404 on this URL;

http://www.tuttoaster.com/code-an-email-newsletter-from-psd-to-html/
