### ISSUE TITLE
403 Twitter

### ISSUE THREAD

**Issue by DaniSpringer** [ocodia/Check-My-Links#86]
Twitter (valid) link returns 403

**Comment by bertnl1943** [comment]
I have the Same problem: Returns 403 errors for any link to Twitter

**Comment by ocodia** [comment]
"HTTP 403 is a standard HTTP status code communicated to clients by an HTTP server to indicate that the server understood the request, but will not fulfill it for some reason related to authorization." 

Nothing I can do about this. Not sure why this has been submitted as an issue.
