### ISSUE TITLE
"Check my links" mostly showing 503

### ISSUE THREAD

**Issue by SebastianSEO** [ocodia/Check-My-Links#87]
Hi there

I just added the extension to my chrome browser. When runnning  "Check my links", the extension mostly show 503 errors, even though the links are working?

**Comment by dgehant** [comment]
I noticed a similar issue on this site.  Is it possible this issue isn't fully resolved?
https://www.homewarrantyreviews.com/us/

A large number of 503 errors (mostly in the footer) that are actually 301s.  When I looked more closely the redirects all involve a minor change: trailing slash on the URL.  

![image](https://user-images.githubusercontent.com/5499008/66509849-a9660c80-ea88-11e9-860a-7ece7c7d3e9d.png)
