### ISSUE TITLE
Check My Links doesn't support local HTML files?

### ISSUE THREAD

**Issue by Bebitoo** [ocodia/Check-My-Links#9]
Hi,
I threw some links on a HTML file, saved the file locally, opened it with Chrome (URL starts with file:///), and ran Check My Links on it: nothing happens :)
Check My Links works fine on, say, www.google.com.
Am I missing something?
## Thanks for your help.

David

**Comment by SecondFlight** [comment]
I'm having this problem on version 3.5.1. The checker won't run if I'm trying to check a local page. I'm using the latest stable chrome build (43.0.2357.81 m).

**Comment by CADbloke** [comment]
Got this problem in Chrome 47.0.2526.106 m Win10x64.
Works fine on teh Internets.
I ticked the box (you should mention that somewhere where yer average LUser will see it)
File attached
[WPFlinks.zip](https://github.com/ocodia/Check-My-Links/files/83872/WPFlinks.zip)

![check my links](https://cloud.githubusercontent.com/assets/147329/12218872/6ecd1a3a-b780-11e5-8690-609e733e1d86.png)

Error message in Console ...
```
extensions::lastError:133 Unchecked runtime.lastError while running tabs.executeScript: Cannot access contents of url "file:///D:/CodezOnD/WPF/WPFlinks.htm". Extension manifest must request permission to access this host.
    at chrome-extension://ojkcdipcgfaekbeaelaapakgnjflfglf/background.js:4:17reportIfUnchecked @ extensions::lastError:133
extensions::lastError:133 Unchecked runtime.lastError while running tabs.executeScript: Cannot access contents of url "file:///D:/CodezOnD/WPF/WPFlinks.htm". Extension manifest must request permission to access this host.
    at chrome-extension://ojkcdipcgfaekbeaelaapakgnjflfglf/background.js:5:17reportIfUnchecked @ extensions::lastError:133
```
